### ISSUE TITLE
Numbers freeze on release

### ISSUE THREAD

**Issue by luis-cruzt** [kiesman99/number_slide_animation#1]
When releasing my app the animation freezes.

![9D9F4621-01A3-4F1C-BA34-977FBE939176](https://user-images.githubusercontent.com/55716036/78086642-cfa39f80-737b-11ea-94c2-747481b12cd1.png)

**Comment by vietz-dev** [comment]
Hey @luiscruzurvenue could you please describe steps to reproduce this?

**Comment by vietz-dev** [comment]
This issue will be closed, because no instructions were provided on how to reproduce this error.

**Comment by nooralibutt** [comment]
I think it happens when you first initialize or use the number slide animation. Any subsequent usage works fine
