### ISSUE TITLE
Selectable option

### ISSUE THREAD

**Issue by nilsreichardt** [kiesman99/number_slide_animation#3]
I think that would be a little difficult to implement, but it would be very nice, to support selectable text as an option. Specially on web it's normal that you can select everything.

**Comment by vietz-dev** [comment]
Thanks for your contribution :)

I see what I can do about that!

**Comment by vietz-dev** [comment]
I've fiddled around with some implementations to make the text selectable, but for now I will close the issue.

This package might get a re-write in which I'll try to target this issue again :)
