### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by nilsreichardt** [kiesman99/number_slide_animation#7]
## Description
All dependencies are migrated to null safety. So we should migrate this package to null safety.

## Resources
* [How to migrate Dart packages to null safety](https://youtu.be/eBr5tlumwlg)
* [Announcing Dart null safety beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730)

**Comment by vietz-dev** [comment]
Hey I'll look into this over the next weeks!

**Comment by nilsreichardt** [comment]
This issue was closed with https://github.com/kiesman99/number_slide_animation/pull/9
